#include "ClamdConfigManager.h"
#include <QFile>
#include <QTextStream>
#include <QStandardPaths>
#include <QTemporaryFile>
#include <QDir>
#include <QFileInfo>
#include <QRegularExpression>

static const char *BEGIN_MARKER = "# --- BEGIN ClamSecurity ---";
static const char *END_MARKER   = "# --- END ClamSecurity ---";

ClamdConfigManager::ClamdConfigManager(QObject *parent)
    : QObject(parent) {}

// ── Static helpers ─────────────────────────────────────────────────────────────

QString ClamdConfigManager::configFilePath()
{
    return QStringLiteral("/etc/clamav/clamd.conf");
}

QString ClamdConfigManager::defaultIncludePath()
{
    return QStandardPaths::writableLocation(QStandardPaths::DownloadLocation);
}

// ── Read config ────────────────────────────────────────────────────────────────

ClamdOnAccessConfig ClamdConfigManager::readConfig() const
{
    ClamdOnAccessConfig cfg;
    // Set sensible default include path
    if (cfg.includePaths.isEmpty()) {
        QString dl = defaultIncludePath();
        if (!dl.isEmpty())
            cfg.includePaths << dl;
    }

    QFile f(configFilePath());
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return cfg;

    QTextStream in(&f);
    bool inSection = false;

    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();

        if (line == QLatin1String(BEGIN_MARKER)) {
            inSection = true;
            // Reset to empty so we don't mix defaults with saved values
            cfg.includePaths.clear();
            cfg.onAccessExcludePaths.clear();
            cfg.excludeFilePatterns.clear();
            continue;
        }
        if (line == QLatin1String(END_MARKER)) {
            inSection = false;
            continue;
        }

        if (!inSection) continue;
        if (line.startsWith('#') || line.isEmpty()) continue;

        // Parse key value pairs
        int space = line.indexOf(' ');
        if (space <= 0) continue;
        QString key = line.left(space).trimmed();
        QString val = line.mid(space + 1).trimmed();

        if (key == "OnAccessPrevention")
            cfg.preventionEnabled = (val.compare("yes", Qt::CaseInsensitive) == 0);
        else if (key == "OnAccessMaxFileSize") {
            // value like "10M"
            QString num = val;
            num.remove(QRegularExpression("[^0-9]"));
            cfg.maxFileSizeMB = num.toInt();
        }
        else if (key == "OnAccessMaxThreads")
            cfg.maxThreads = val.toInt();
        else if (key == "OnAccessDenyOnError")
            cfg.denyOnError = (val.compare("yes", Qt::CaseInsensitive) == 0);
        else if (key == "OnAccessExcludeUname")
            cfg.excludeUname = val;
        else if (key == "OnAccessIncludePath")
            cfg.includePaths << val;
        else if (key == "OnAccessExcludePath")
            cfg.onAccessExcludePaths << val;
        else if (key == "ExcludePath")
            cfg.excludeFilePatterns << val;
        else if (key == "OnAccessExtraScanning")
            cfg.extraScanning = (val.compare("yes", Qt::CaseInsensitive) == 0);
        else if (key == "DisableDDD")
            cfg.disableDDD = (val.compare("yes", Qt::CaseInsensitive) == 0);
    }

    return cfg;
}

// ── Build section ──────────────────────────────────────────────────────────────

QString ClamdConfigManager::buildSection(const ClamdOnAccessConfig &cfg) const
{
    QStringList lines;
    lines << QLatin1String(BEGIN_MARKER);
    lines << "# Generated by ClamSecurity. Edit via Settings > Protection tab.";
    lines << QString("OnAccessPrevention %1").arg(cfg.preventionEnabled ? "yes" : "no");
    lines << QString("OnAccessMaxFileSize %1M").arg(cfg.maxFileSizeMB);
    lines << QString("OnAccessMaxThreads %1").arg(cfg.maxThreads);
    lines << QString("OnAccessDenyOnError %1").arg(cfg.denyOnError ? "yes" : "no");
    lines << QString("OnAccessExtraScanning %1").arg(cfg.extraScanning ? "yes" : "no");
    if (cfg.disableDDD)
        lines << "DisableDDD yes";

    // Include paths (monitored folders)
    for (const QString &path : cfg.includePaths)
        if (!path.isEmpty())
            lines << "OnAccessIncludePath " + path;

    // Always-excluded system paths
    static const QStringList systemExclude = {"/proc", "/sys", "/dev"};
    QStringList excludePaths = cfg.onAccessExcludePaths;
    for (const QString &sp : systemExclude)
        if (!excludePaths.contains(sp))
            excludePaths.prepend(sp);

    for (const QString &path : excludePaths)
        if (!path.isEmpty())
            lines << "OnAccessExcludePath " + path;

    lines << "OnAccessExcludeUname " + cfg.excludeUname;

    // File extension/pattern exclusions (PCRE)
    for (const QString &pat : cfg.excludeFilePatterns)
        if (!pat.isEmpty())
            lines << "ExcludePath " + pat;

    lines << QLatin1String(END_MARKER);
    return lines.join('\n') + '\n';
}

// ── Save config ────────────────────────────────────────────────────────────────

void ClamdConfigManager::saveConfig(const ClamdOnAccessConfig &cfg)
{
    if (m_copyProcess) return; // already in progress

    // Read existing file content, strip old ClamSecurity section
    QFile orig(configFilePath());
    QString existingContent;
    if (orig.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QTextStream in(&orig);
        bool skip = false;
        while (!in.atEnd()) {
            QString line = in.readLine();
            if (line.trimmed() == QLatin1String(BEGIN_MARKER)) {
                skip = true;
                continue;
            }
            if (line.trimmed() == QLatin1String(END_MARKER)) {
                skip = false;
                continue;
            }
            if (!skip)
                existingContent += line + '\n';
        }
        orig.close();
    }

    // Append new section
    QString newContent = existingContent + buildSection(cfg);

    // Write to a temp file
    QTemporaryFile tmp;
    tmp.setAutoRemove(false);
    if (!tmp.open()) {
        emit configSaved(false, tr("Could not create temporary file."));
        return;
    }
    tmp.write(newContent.toUtf8());
    tmp.close();
    m_tempPath = tmp.fileName();

    // Copy with pkexec (async)
    m_copyProcess = new QProcess(this);
    connect(m_copyProcess,
            qOverload<int, QProcess::ExitStatus>(&QProcess::finished),
            this, &ClamdConfigManager::onCopyFinished);
    m_copyProcess->start("pkexec", {"cp", m_tempPath, configFilePath()});
}

void ClamdConfigManager::onCopyFinished(int exitCode, QProcess::ExitStatus)
{
    m_copyProcess->deleteLater();
    m_copyProcess = nullptr;

    // Clean up temp file
    QFile::remove(m_tempPath);
    m_tempPath.clear();

    if (exitCode == 0) {
        // Restart services
        QProcess::startDetached("pkexec",
            {"systemctl", "restart", "clamav-daemon"});
        QProcess::startDetached("pkexec",
            {"systemctl", "restart", "clamav-clamonacc"});
        emit configSaved(true,
            tr("Configuration saved. Services are restarting."));
    } else if (exitCode == 127) {
        emit configSaved(false, tr("Operation cancelled by user."));
    } else {
        emit configSaved(false,
            tr("Failed to write configuration (exit code %1).").arg(exitCode));
    }
}
