#!/usr/bin/env bash
# ClamSecurity install script
# Installs and configures ClamAV + clamav-clamonacc for use with ClamSecurity
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()     { error "$*"; exit 1; }

# ── Detect distribution ────────────────────────────────────────────────────────
detect_distro() {
    if command -v pacman &>/dev/null; then
        echo "arch"
    elif command -v apt-get &>/dev/null; then
        echo "debian"
    elif command -v dnf &>/dev/null; then
        echo "fedora"
    else
        echo "unknown"
    fi
}

# ── Install ClamAV packages ────────────────────────────────────────────────────
install_clamav() {
    local distro="$1"
    info "Installing ClamAV packages for distro: $distro"

    case "$distro" in
        arch)
            sudo pacman -Sy --noconfirm --needed clamav
            ;;
        debian)
            sudo apt-get update -qq
            sudo apt-get install -y clamav clamav-daemon
            ;;
        fedora)
            sudo dnf install -y clamav clamav-update clamd
            ;;
        *)
            die "Unsupported distribution. Please install ClamAV manually."
            ;;
    esac
    info "ClamAV packages installed."
}

# ── Enable and start clamav-daemon ────────────────────────────────────────────
setup_daemon() {
    info "Enabling and starting clamav-daemon..."
    if systemctl is-enabled --quiet clamav-daemon 2>/dev/null; then
        info "clamav-daemon already enabled."
    else
        sudo systemctl enable clamav-daemon || warn "Could not enable clamav-daemon."
    fi
    sudo systemctl start clamav-daemon || warn "Could not start clamav-daemon (it may start after freshclam)."
}

# ── Create clamav-clamonacc systemd override ──────────────────────────────────
setup_clamonacc_service() {
    info "Configuring clamav-clamonacc service override..."
    local override_dir="/etc/systemd/system/clamav-clamonacc.service.d"
    local override_file="$override_dir/override.conf"

    sudo mkdir -p "$override_dir"
    sudo tee "$override_file" > /dev/null <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/sbin/clamonacc -F --log=/var/log/clamav/clamonacc.log
EOF
    sudo systemctl daemon-reload
    info "clamav-clamonacc override configured."
}

# ── Configure /etc/clamav/clamd.conf with ClamSecurity section ────────────────
configure_clamd_conf() {
    local conf_file="/etc/clamav/clamd.conf"
    local default_path="$HOME/Downloads"

    if [ ! -f "$conf_file" ]; then
        warn "$conf_file does not exist. Skipping ClamSecurity section injection."
        return
    fi

    info "Configuring $conf_file with ClamSecurity section..."

    # Remove any existing ClamSecurity section first
    local tmp_file
    tmp_file=$(mktemp)
    awk '/^# --- BEGIN ClamSecurity ---/{skip=1} !skip{print} /^# --- END ClamSecurity ---/{skip=0}' \
        "$conf_file" > "$tmp_file"

    # Append new section
    cat >> "$tmp_file" <<EOF

# --- BEGIN ClamSecurity ---
# Generated by ClamSecurity install script. Edit via Settings > Protection tab.
OnAccessPrevention yes
OnAccessMaxFileSize 10M
OnAccessMaxThreads 4
OnAccessDenyOnError no
OnAccessExtraScanning yes
OnAccessIncludePath $default_path
OnAccessExcludePath /proc
OnAccessExcludePath /sys
OnAccessExcludePath /dev
OnAccessExcludeUname clamav
ExcludePath \\.crdownload\$
ExcludePath \\.part\$
# --- END ClamSecurity ---
EOF

    sudo cp "$tmp_file" "$conf_file"
    rm -f "$tmp_file"
    info "clamd.conf configured."
}

# ── Enable and start clamav-clamonacc ─────────────────────────────────────────
setup_clamonacc() {
    info "Enabling clamav-clamonacc service..."
    sudo systemctl enable clamav-clamonacc || warn "Could not enable clamav-clamonacc."
    # Don't start now — it needs daemon to be fully up first
    info "clamav-clamonacc will start automatically with the system."
}

# ── Update virus signatures ────────────────────────────────────────────────────
update_signatures() {
    info "Updating ClamAV virus signatures (this may take a few minutes)..."
    # Stop freshclam timer if running to avoid lock conflicts
    sudo systemctl stop clamav-freshclam 2>/dev/null || true
    if sudo freshclam; then
        info "Virus signatures updated successfully."
    else
        warn "freshclam encountered an error. Signatures may be partially updated."
    fi
    sudo systemctl start clamav-freshclam 2>/dev/null || true
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo "═══════════════════════════════════════════════════════"
    echo "   ClamSecurity — ClamAV Setup Script"
    echo "═══════════════════════════════════════════════════════"
    echo ""

    if [ "$EUID" -eq 0 ]; then
        die "Do not run this script as root. It will use sudo when needed."
    fi

    DISTRO=$(detect_distro)
    info "Detected distribution: $DISTRO"

    install_clamav "$DISTRO"
    configure_clamd_conf
    setup_clamonacc_service
    setup_daemon
    setup_clamonacc
    update_signatures

    echo ""
    echo "═══════════════════════════════════════════════════════"
    info "Installation complete!"
    echo ""
    echo "  Next steps:"
    echo "  1. Launch ClamSecurity"
    echo "  2. Go to Settings > Protection to configure real-time protection"
    echo "  3. Enable 'Real-Time Protection' from the main window"
    echo ""
    warn "Note: Real-time protection (clamav-clamonacc) requires"
    warn "the kernel to have fanotify support enabled."
    echo "═══════════════════════════════════════════════════════"
}

main "$@"
